# Generated by Django 4.2 on 2026-06-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_session_roll_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('designation', models.CharField(help_text='Designation (e.g. Senior Lecturer, Assistant Professor).', max_length=100)),
                ('department', models.CharField(help_text='Department (e.g. Computer Science, English).', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this faculty member is active.')),
                ('assigned_sessions', models.ManyToManyField(blank=True, help_text='Sessions assigned to this faculty member.', related_name='faculty_members', to='academics.session')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User account for the faculty member.', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Profile',
                'verbose_name_plural': 'Faculty Profiles',
            },
        ),
    ]
