# Generated by Django 4.2 on 2026-07-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Faculty profile picture. Allowed: JPG, PNG, WEBP. Max 2 MB.', null=True, upload_to='faculty/profile_pictures/'),
        ),
    ]
