# Generated by Django 4.2 on 2026-06-13 13:55

import apps.accounts.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Used as login identifier. Must be unique.', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Mobile phone number.', max_length=15, null=True)),
                ('cnic', models.CharField(blank=True, help_text='National ID card number.', max_length=15, null=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='User profile photograph.', null=True, upload_to=apps.accounts.models.user_profile_photo_path)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', help_text='Account status. Inactive users cannot log in.', max_length=10)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts.')),
                ('lockout_until', models.DateTimeField(blank=True, help_text='Account locked until this time due to failed attempts.', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last successful login.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('cnic_photo', models.ImageField(blank=True, help_text='Scan of national ID card.', null=True, upload_to=apps.accounts.models.user_cnic_photo_path)),
                ('degree_photo', models.ImageField(blank=True, help_text='Scan of highest degree.', null=True, upload_to=apps.accounts.models.user_degree_photo_path)),
                ('address', models.TextField(blank=True, help_text='Residential address.', null=True)),
                ('joining_date', models.DateField(blank=True, help_text='Employment start date.', null=True)),
                ('specialization', models.CharField(blank=True, help_text='Subject expertise (primarily for teachers).', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography.', null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact phone number.', max_length=15, null=True)),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['status', 'is_active'], name='idx_user_status_active'),
        ),
    ]
