# Generated by Django 4.2 on 2026-06-15 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_is_selected_studentachievement'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('CSS', 'CSS'), ('PMS', 'PMS'), ('PPSC', 'PPSC'), ('FPSC', 'FPSC'), ('OTHER', 'OTHER')], max_length=10)),
                ('year', models.IntegerField()),
                ('rank', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_achievements', to=settings.AUTH_USER_MODEL)),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='documents.comparisonjob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='students.student')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-year', 'exam_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('student', 'exam_type', 'year'), name='unique_student_exam_year'),
        ),
    ]
