# Generated by Django 4.2 on 2026-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='testimonial',
            field=models.TextField(blank=True, default=''),
        ),
    ]
