# Generated by Django 4.2 on 2026-06-13 13:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(db_index=True, help_text='When the expense occurred.')),
                ('description', models.TextField(help_text='What the expense was for.')),
                ('receipt_file', models.FileField(blank=True, help_text='Scan of expense receipt.', null=True, upload_to='expense_receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval workflow status.', max_length=15)),
                ('rejection_reason', models.CharField(blank=True, help_text='Reason if the expense was rejected.', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('name', models.CharField(help_text='Category name (e.g., Rent, Utilities).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently in use.')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('installment_number', models.PositiveSmallIntegerField(help_text='Sequence number within the plan (1, 2, 3...).')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount due for this installment.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField(db_index=True, help_text='When this installment is due.')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually paid against this installment.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_date', models.DateField(blank=True, help_text='When this installment was paid.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='pending', help_text='Current installment payment status.', max_length=10)),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount being split into installments.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('number_of_installments', models.PositiveSmallIntegerField(help_text='How many installments.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this plan is currently active.')),
                ('notes', models.TextField(blank=True, help_text='Plan notes or special terms.', null=True)),
            ],
            options={
                'verbose_name': 'Installment Plan',
                'verbose_name_plural': 'Installment Plans',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payment amount. Always >= 0.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateField(db_index=True, help_text='Date payment was received.')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('BankTransfer', 'Bank Transfer'), ('Online', 'Online Payment'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', help_text='How the payment was made.', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('refunded', 'Refunded')], db_index=True, default='confirmed', help_text='Current payment status.', max_length=15)),
                ('receipt_number', models.CharField(blank=True, help_text='Auto-generated receipt identifier.', max_length=30, null=True, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='Bank or online transaction reference.', max_length=50, null=True)),
                ('month', models.CharField(blank=True, db_index=True, help_text='YYYY-MM for monthly sessions and late fee tracking.', max_length=7, null=True)),
                ('is_late_fee_payment', models.BooleanField(db_index=True, default=False, help_text='Separates late fee from regular revenue.')),
                ('late_fee_waived', models.BooleanField(default=False, help_text='Whether this is a waiver record.')),
                ('late_fee_waiver_reason', models.CharField(blank=True, help_text='Reason for late fee waiver.', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes or remarks.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount. Can be partial.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(help_text='Reason for the refund.')),
                ('refund_date', models.DateField(db_index=True, help_text='When the refund was processed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Refund approval status.', max_length=15)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Staff who approved the refund.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(help_text='The original payment being refunded.', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.payment')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff who processed the refund.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-refund_date'],
            },
        ),
    ]
