# Generated by Django 4.2 on 2026-06-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(help_text='Which enrollment this payment is for.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='late_fee_waived_by',
            field=models.ForeignKey(blank=True, help_text='Who approved the late fee waiver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_late_fee_waivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Staff who recorded this payment. Null if user was deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='enrollment',
            field=models.ForeignKey(help_text='The enrollment this plan belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installment',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Linked payment record when paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_links', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='installment',
            name='plan',
            field=models.ForeignKey(help_text='Parent installment plan.', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.installmentplan'),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff who approved this expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='Expense category.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Staff who recorded this expense. Null if user was deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['enrollment', 'payment_status'], name='idx_pay_enroll_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status', 'is_late_fee_payment'], name='idx_pay_status_latefee'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['enrollment', 'is_active'], name='idx_instplan_enroll_active'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['plan', 'installment_number'], name='idx_inst_plan_number'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('plan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date', 'status'], name='idx_expense_date_status'),
        ),
    ]
