# Generated by Django 4.2 on 2026-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated receipt identifier. Uniqueness enforced in clean().', max_length=30, null=True),
        ),
    ]
