# Generated by Django 4.2 on 2026-06-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_classschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('fee_type', models.CharField(choices=[('one_time', 'One Time Payment'), ('monthly', 'Monthly Installments')], default='one_time', max_length=20, verbose_name='Fee Type')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_installments', models.PositiveIntegerField(default=1, help_text='Number of monthly installments. Use 1 for one-time payment.')),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount per monthly installment.', max_digits=10, null=True)),
                ('due_day', models.PositiveIntegerField(default=10, help_text='Day of month payment is due (1-28).')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.session')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
