# Generated by Django 4.2 on 2026-06-13 13:55

import apps.academics.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted.', null=True)),
                ('name', models.CharField(db_index=True, help_text='Session or course name.', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Short code for roll number generation (e.g., CSS, PMS).', max_length=20, null=True, unique=True)),
                ('session_type', models.CharField(choices=[('time_period', 'Time Period Session'), ('monthly', 'Monthly Session')], default='time_period', help_text='Whether this is a fixed-duration or monthly-billing session.', max_length=15)),
                ('description', models.TextField(blank=True, help_text='Session description and details.', null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, help_text='Session start date.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Session end date.', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Session display photo.', null=True, upload_to=apps.academics.models.session_photo_path)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base fee for this session.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('registration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time registration fee.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], db_index=True, default='Active', help_text='Current session status.', max_length=15)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Enrollment capacity. Null means unlimited.', null=True)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fee charged per overdue period. 0 means no late fee.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('late_fee_grace_days', models.PositiveIntegerField(default=10, help_text='Days after due_day before late fee is applied.')),
                ('late_fee_maximum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum cumulative late fee. 0 means no cap.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_day', models.PositiveSmallIntegerField(default=10, help_text='Day of month payments are due (1-28).')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('name', models.CharField(help_text='Subject name.', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Subject code (e.g., MATH101).', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Subject description.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently offered.')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('assigned_from', models.DateField(blank=True, help_text='Start of teaching assignment.', null=True)),
                ('assigned_until', models.DateField(blank=True, help_text='End of teaching assignment. Null means ongoing.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this assignment is currently active.')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
            },
        ),
    ]
