# Generated by Django 4.2 on 2026-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Short code for roll number generation. Uniqueness enforced in clean().', max_length=20, null=True),
        ),
    ]
