# Generated by Django 4.2 on 2026-06-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='roll_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix used for session-based automatic roll number generation.', max_length=10),
        ),
    ]
