# Generated by Django 4.2 on 2026-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_session_roll_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='Academic year (e.g. 2026, 2026-2027).', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='batch_number',
            field=models.CharField(blank=True, default='', help_text='Batch identifier or number.', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='is_admission_open',
            field=models.BooleanField(default=True, help_text='Designates whether new student registrations are open.'),
        ),
        migrations.AddField(
            model_name='session',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum seat capacity (ERP Operations).', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_category',
            field=models.CharField(choices=[('CSS', 'CSS'), ('PPSC_FPSC', 'PPSC/FPSC'), ('PMS', 'PMS'), ('OLEVEL', 'O-Level'), ('ALEVEL', 'A-Level'), ('IELTS', 'IELTS'), ('CADET_COLLEGE', 'Cadet College'), ('PTE', 'PTE'), ('MINISTERIAL', 'Ministerial'), ('OTHER', 'Other')], default='OTHER', help_text='Classification category for this session.', max_length=20),
        ),
    ]
