# Generated by Django 4.2 on 2026-06-14 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
        ('academics', '0005_session_academic_year_session_batch_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week for this class.', max_length=15)),
                ('start_time', models.TimeField(help_text='Start time of the class.')),
                ('end_time', models.TimeField(help_text='End time of the class.')),
                ('classroom', models.CharField(help_text='Classroom name or identifier.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is active.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(help_text='The assigned faculty member.', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.facultyprofile')),
                ('session', models.ForeignKey(help_text='The session for this schedule.', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.session')),
                ('subject', models.ForeignKey(help_text='The subject being taught.', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.subject')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
