# Generated by Django 4.2 on 2026-06-13 13:54

import apps.students.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted.', null=True)),
                ('roll_number', models.CharField(blank=True, help_text='Unique roll number, generated on first enrollment.', max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(db_index=True, help_text='Student full name.', max_length=100)),
                ('father_name', models.CharField(blank=True, help_text='Father or guardian name.', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Student email address. Uniqueness enforced in clean() for non-null values.', max_length=254, null=True)),
                ('cnic', models.CharField(blank=True, help_text='Student or parent CNIC number.', max_length=15, null=True)),
                ('phone', models.CharField(blank=True, help_text='Primary contact number.', max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth for age calculation.', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Student gender.', max_length=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed'), ('Alumni', 'Alumni')], db_index=True, default='Active', help_text='Current lifecycle status.', max_length=15)),
                ('inactive_reason', models.CharField(blank=True, choices=[('', 'None'), ('Freeze', 'Freeze'), ('Left', 'Left'), ('Expelled', 'Expelled')], default='', help_text='Reason for inactive status.', max_length=15)),
                ('last_degree', models.CharField(blank=True, help_text='Last educational qualification.', max_length=100, null=True)),
                ('last_institution', models.CharField(blank=True, help_text='Name of last institution attended.', max_length=100, null=True)),
                ('address_temporary', models.TextField(blank=True, help_text='Current residential address.', null=True)),
                ('address_permanent', models.TextField(blank=True, help_text='Permanent home address.', null=True)),
                ('admission_date', models.DateField(blank=True, db_index=True, help_text='Date of first admission to the academy.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this student.', null=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Staff member who registered this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_students', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('portal_user', models.OneToOneField(blank=True, help_text='Linked user account for student portal access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_record', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('document_type', models.CharField(choices=[('profile_photo', 'Profile Photo'), ('cnic_front', 'CNIC Front'), ('cnic_back', 'CNIC Back'), ('degree', 'Degree Certificate'), ('certificate', 'Other Certificate'), ('other', 'Other Document')], help_text='Category of this document.', max_length=30)),
                ('title', models.CharField(blank=True, help_text='Display name for this document.', max_length=100, null=True)),
                ('file', models.FileField(help_text='The uploaded file.', upload_to=apps.students.models.student_document_path)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes, set on upload.', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='Detected MIME type of the file.', max_length=100, null=True)),
                ('student', models.ForeignKey(help_text='The student this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Staff who uploaded this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('name', models.CharField(db_index=True, help_text='Name of the person inquiring.', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Contact email. Not unique - same person may inquire multiple times.', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=15, null=True)),
                ('area_of_residence', models.CharField(blank=True, help_text='Location for demographic tracking.', max_length=150, null=True)),
                ('inquiry_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='When the inquiry came in.')),
                ('inquiry_source', models.CharField(choices=[('Call', 'Phone Call'), ('Message', 'Message'), ('PhysicalVisit', 'Physical Visit'), ('Online', 'Online'), ('Referral', 'Referral'), ('SocialMedia', 'Social Media')], default='Call', help_text='How the lead reached us.', max_length=20)),
                ('follow_up_date', models.DateField(blank=True, db_index=True, help_text='Next scheduled follow-up date.', null=True)),
                ('follow_up_notes', models.TextField(blank=True, help_text='Notes from follow-up conversations.', null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Converted', 'Converted'), ('Lost', 'Lost')], db_index=True, default='New', help_text='Current lead pipeline status.', max_length=15)),
                ('loss_reason', models.CharField(blank=True, help_text='Why this lead was marked as lost.', max_length=200, null=True)),
                ('converted_student', models.ForeignKey(blank=True, help_text='Links to Student record after conversion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='students.student')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, help_text='Staff member handling this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_leads', to=settings.AUTH_USER_MODEL)),
                ('interested_session', models.ForeignKey(blank=True, help_text='Session they inquired about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='academics.session')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-inquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('full_name', models.CharField(help_text='Guardian full name.', max_length=100)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Sibling', 'Sibling'), ('Other', 'Other')], default='Father', help_text='Relationship to the student.', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Guardian contact number.', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Guardian email address.', max_length=254, null=True)),
                ('cnic', models.CharField(blank=True, help_text='Guardian CNIC number.', max_length=15, null=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this is the primary contact for the student.')),
                ('is_emergency_contact', models.BooleanField(default=False, help_text='Whether this guardian is an emergency contact.')),
                ('occupation', models.CharField(blank=True, help_text='Guardian occupation.', max_length=100, null=True)),
                ('address', models.TextField(blank=True, help_text='Guardian residential address.', null=True)),
                ('portal_user', models.OneToOneField(blank=True, help_text='Linked user account for parent portal access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_record', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student this guardian is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted.', null=True)),
                ('registration_date', models.DateField(blank=True, help_text='Date of enrollment.', null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Override of session registration fee. Null uses session default.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee', models.DecimalField(blank=True, decimal_places=2, help_text='Override of session fee. Null uses session default.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount applied to this enrollment.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_reason', models.CharField(blank=True, help_text='Scholarship or discount justification.', max_length=200, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment due date for time-period sessions.', null=True)),
                ('next_monthly_due', models.DateField(blank=True, help_text='Next monthly due date for monthly sessions.', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Frozen', 'Frozen'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn'), ('Transferred', 'Transferred')], db_index=True, default='Active', help_text='Current enrollment status.', max_length=15)),
                ('freeze_date', models.DateField(blank=True, help_text='Date when enrollment was frozen.', null=True)),
                ('freeze_reason', models.CharField(blank=True, help_text='Reason for freezing enrollment.', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this enrollment.', null=True)),
                ('is_fee_waived', models.BooleanField(default=False, help_text='Full fee waiver flag.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('enrolled_by', models.ForeignKey(blank=True, help_text='Staff who enrolled this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The session enrolled in. PROTECT prevents cascade conflict with Payment.', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.session')),
                ('student', models.ForeignKey(help_text='The enrolled student.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('transferred_from', models.ForeignKey(blank=True, help_text='Source enrollment if this is a transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to='students.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['student', 'document_type'], name='idx_stdoc_student_type'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'created_at'], name='idx_student_status_created'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'follow_up_date'], name='idx_lead_status_followup'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['student', 'is_primary'], name='idx_guard_student_primary'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['session', 'status'], name='idx_enroll_session_status'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='idx_enroll_student_status'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['due_date'], name='idx_enroll_due_date'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['next_monthly_due'], name='idx_enroll_monthly_due'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'session')},
        ),
    ]
