# Generated by Django 4.2 on 2026-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique roll number, generated on first enrollment. Uniqueness enforced in clean().', max_length=20, null=True),
        ),
    ]
