# Generated by Django 4.2 on 2026-06-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_low_attendance',
            field=models.BooleanField(default=False, help_text='Flagged if student attendance falls below 70%.'),
        ),
    ]
