# Generated by Django 4.2 on 2026-06-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('password_change', 'Password Change')], db_index=True, help_text='Type of action performed.', max_length=20)),
                ('model_name', models.CharField(db_index=True, help_text='App label and model name (e.g., students.Student).', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='Primary key of the affected object, stored as string.', max_length=50, null=True)),
                ('changes', models.TextField(blank=True, help_text='JSON-serialized diff of changed fields.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request.', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string.', max_length=500, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred.')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='idx_audit_user_time'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='idx_audit_model_obj'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='idx_audit_action_time'),
        ),
    ]
