# Generated by Django 4.2 on 2026-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Admin', 'Admin'), ('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Accountant', 'Accountant'), ('Registrar', 'Registrar'), ('Student', 'Student'), ('Guardian', 'Guardian')], db_index=True, max_length=20)),
                ('module_name', models.CharField(choices=[('finance', 'Finance'), ('exams', 'Exams'), ('attendance', 'Attendance'), ('students', 'Students'), ('notifications', 'Notifications')], db_index=True, max_length=30)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role_name', 'module_name'], name='idx_role_mod_perm'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role_name', 'module_name')},
        ),
    ]
