# Generated by Django 4.2 on 2026-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_rolepermission_idx_role_mod_perm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module_name',
            field=models.CharField(choices=[('finance', 'Finance'), ('exams', 'Exams'), ('attendance', 'Attendance'), ('students', 'Students'), ('notifications', 'Notifications'), ('users', 'Users')], db_index=True, max_length=30),
        ),
    ]
