# Generated by Django 4.2 on 2026-06-15 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_has_low_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='comparison_jobs/')),
                ('exam_type', models.CharField(choices=[('CSS', 'CSS'), ('PMS', 'PMS'), ('PPSC', 'PPSC'), ('FPSC', 'FPSC'), ('OTHER', 'OTHER')], default='OTHER', max_length=10)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('matched_entries', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Processed', 'Processed'), ('Failed', 'Failed')], default='Uploaded', max_length=15)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comparison Job',
                'verbose_name_plural': 'Comparison Jobs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_name', models.CharField(max_length=255)),
                ('extracted_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('is_exact_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='documents.comparisonjob')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_results', to='students.student')),
            ],
            options={
                'verbose_name': 'Comparison Result',
                'verbose_name_plural': 'Comparison Results',
                'ordering': ['-match_confidence'],
            },
        ),
    ]
