# Generated by Django 4.2 on 2026-06-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Which date is locked.')),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the lock was applied.')),
                ('reason', models.CharField(blank=True, help_text='Reason for locking.', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Attendance Lock',
                'verbose_name_plural': 'Attendance Locks',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('date', models.DateField(db_index=True, help_text='Date of attendance.')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], help_text='Attendance status for this date.', max_length=10)),
                ('remarks', models.CharField(blank=True, help_text='Optional note (e.g., reason for absence).', max_length=200, null=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='Staff or teacher who marked attendance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Which session this attendance is for.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.session')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
            },
        ),
    ]
