# Generated by Django 4.2 on 2026-06-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '__first__'),
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(help_text='Which student.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendancelock',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='Who locked this date. Null if user was deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_locks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancelock',
            name='session',
            field=models.ForeignKey(help_text='Which session is locked.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_locks', to='academics.session'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'date'], name='idx_attend_session_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'session'], name='idx_attend_student_session'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancelock',
            unique_together={('session', 'date')},
        ),
    ]
