# Generated by Django 4.2 on 2026-06-13 13:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('name', models.CharField(help_text='Exam name (e.g., Midterm 1, Final Exam).', max_length=100)),
                ('exam_type', models.CharField(choices=[('Quiz', 'Quiz'), ('Test', 'Test'), ('Midterm', 'Midterm'), ('Final', 'Final Exam'), ('Assignment', 'Assignment'), ('Project', 'Project')], default='Test', help_text='Type of assessment.', max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Maximum possible marks.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('passing_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum marks to pass. Null means no passing threshold.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('exam_date', models.DateField(blank=True, db_index=True, help_text='When the exam is held.', null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Weightage for weighted averaging (1.00 = 100%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_published', models.BooleanField(default=False, help_text='Whether results are visible to students and parents.')),
                ('description', models.TextField(blank=True, help_text='Exam instructions or notes.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Which session this exam belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.session')),
                ('subject', models.ForeignKey(blank=True, help_text='Specific subject if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.subject')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-exam_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('grade_name', models.CharField(help_text='Grade label (A+, A, B+, B, etc.).', max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, help_text='Minimum percentage for this grade (inclusive).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('max_percentage', models.DecimalField(decimal_places=2, help_text='Maximum percentage for this grade (inclusive).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='GPA point value if applicable.', max_digits=4, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display ordering (lower = higher grade).')),
                ('session', models.ForeignKey(blank=True, help_text='Null means global default grading scale.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_configs', to='academics.session')),
            ],
            options={
                'verbose_name': 'Grade Configuration',
                'verbose_name_plural': 'Grade Configurations',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks scored by the student.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: (marks_obtained / total_marks) * 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('grade', models.CharField(blank=True, help_text='Auto-assigned from GradeConfig.', max_length=5, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Auto-calculated rank within the exam.', null=True)),
                ('is_absent', models.BooleanField(default=False, help_text='Student was absent for the exam.')),
                ('remarks', models.TextField(blank=True, help_text='Teacher remarks on performance.', null=True)),
                ('entered_by', models.ForeignKey(blank=True, help_text='Staff or teacher who entered the marks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_exam_results', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(help_text='Which exam.', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(help_text='Which student.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-marks_obtained'],
            },
        ),
        migrations.AddIndex(
            model_name='gradeconfig',
            index=models.Index(fields=['session', 'min_percentage'], name='idx_grade_session_minpct'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeconfig',
            unique_together={('session', 'grade_name')},
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'marks_obtained'], name='idx_result_exam_marks'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['session', 'subject'], name='idx_exam_session_subject'),
        ),
    ]
