# Generated by Django 4.2 on 2026-06-14 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the exam was reviewed.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The principal or admin who reviewed the exam results.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Under Review', 'Under Review'), ('Published', 'Published')], default='Draft', help_text='Approval status of the exam results.', max_length=20),
        ),
    ]
