# Generated by Django 4.2 on 2026-06-15 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_is_selected_studentachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0006_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Applicant full name.', max_length=200)),
                ('father_name', models.CharField(help_text="Father's full name.", max_length=200)),
                ('email', models.EmailField(help_text='Contact email address.', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number.', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Applicant date of birth.')),
                ('cnic', models.CharField(blank=True, help_text='Applicant CNIC/B-Form.', max_length=15)),
                ('address', models.TextField(blank=True, help_text='Postal address.')),
                ('exam_type', models.CharField(choices=[('CSS', 'CSS'), ('PPSC_FPSC', 'PPSC/FPSC'), ('PMS', 'PMS'), ('OLEVEL', 'O-Level'), ('ALEVEL', 'A-Level'), ('IELTS', 'IELTS'), ('CADET_COLLEGE', 'Cadet College'), ('PTE', 'PTE'), ('MINISTERIAL', 'Ministerial'), ('OTHER', 'Other')], help_text='Exam category classification.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', help_text='Current status of the admission application.', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Internal staff remarks.')),
                ('converted_student', models.ForeignKey(blank=True, help_text='Linked student record post-conversion.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who submitted this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
                ('desired_session', models.ForeignKey(blank=True, help_text='Target academic session.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.session')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff user who reviewed this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cnic', 'CNIC / B-Form'), ('photo', 'Profile Photograph'), ('academic_certificate', 'Academic Certificate'), ('other', 'Other Document')], help_text='Category of the document.', max_length=30)),
                ('file', models.FileField(help_text='Uploaded document file.', upload_to='admission_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='The linked admission application.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionapplication')),
            ],
        ),
    ]
