# Generated by Django 4.2 on 2026-06-13 13:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('model_type', models.CharField(choices=[('dropout', 'Dropout Prediction'), ('revenue', 'Revenue Prediction'), ('performance', 'Performance Prediction'), ('payment_anomaly', 'Payment Anomaly Detection'), ('attendance_risk', 'Attendance Risk Detection')], db_index=True, help_text='Which prediction model this version is for.', max_length=30)),
                ('version', models.CharField(help_text='Semantic version string (e.g., 1.0.0).', max_length=20)),
                ('file_path', models.CharField(help_text='Path to the serialized model file (.joblib).', max_length=500)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=4, help_text='Model accuracy (0.0000 to 1.0000).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('precision_score', models.DecimalField(blank=True, decimal_places=4, help_text='Model precision (0.0000 to 1.0000).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('recall_score', models.DecimalField(blank=True, decimal_places=4, help_text='Model recall (0.0000 to 1.0000).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('training_samples', models.PositiveIntegerField(blank=True, help_text='Number of training samples used.', null=True)),
                ('feature_list', models.TextField(blank=True, help_text='JSON list of feature names used in training.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one active version per model_type.')),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this model version was trained.')),
                ('notes', models.TextField(blank=True, help_text='Training notes, hyperparameters, changelog.', null=True)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('prediction_type', models.CharField(choices=[('dropout', 'Dropout Risk'), ('revenue', 'Revenue Forecast'), ('performance', 'Performance Prediction'), ('payment_anomaly', 'Payment Anomaly'), ('attendance_risk', 'Attendance Risk')], db_index=True, help_text='Category of this prediction.', max_length=30)),
                ('target_model', models.CharField(help_text='Target model name (e.g., students.Student).', max_length=50)),
                ('target_object_id', models.PositiveIntegerField(db_index=True, help_text='Primary key of the target object.')),
                ('input_features', models.TextField(blank=True, help_text='JSON of input features used for this prediction.', null=True)),
                ('prediction_value', models.TextField(help_text='JSON of prediction output.')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Prediction confidence (0.00 to 100.00).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, help_text='Categorized risk level.', max_length=10, null=True)),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Whether staff has reviewed this prediction.')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When this prediction was acknowledged.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When this prediction becomes stale.', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='Staff who reviewed this prediction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_predictions', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(blank=True, help_text='Which model version produced this prediction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='ai_engine.modelversion')),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['model_type', 'is_active'], name='idx_modelver_type_active'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['target_model', 'target_object_id'], name='idx_pred_target'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['prediction_type', 'risk_level'], name='idx_pred_type_risk'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['is_acknowledged', 'prediction_type'], name='idx_pred_ack_type'),
        ),
    ]
