# Generated by Django 4.2 on 2026-06-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, help_text='Where the email was sent.', max_length=254)),
                ('subject', models.CharField(help_text='Email subject line.', max_length=200)),
                ('body_preview', models.CharField(blank=True, help_text='First 500 characters of body for quick reference.', max_length=500, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], db_index=True, default='sent', help_text='Email delivery status.', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if delivery failed.', null=True)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the email was dispatched.')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('category', models.CharField(choices=[('General', 'General'), ('LateFee', 'Late Fee'), ('NewEntry', 'New Entry'), ('Deletion', 'Deletion'), ('Payment', 'Payment'), ('Attendance', 'Attendance'), ('ExamResult', 'Exam Result'), ('MonthlyRenewal', 'Monthly Renewal'), ('System', 'System')], db_index=True, default='General', help_text='Notification category for filtering.', max_length=25)),
                ('title', models.CharField(help_text='Short notification title.', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Notification body text.', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the user has read this notification.')),
                ('related_model', models.CharField(blank=True, help_text='Model name of related object (e.g., students.Student).', max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the related object.', null=True)),
                ('dedup_key', models.CharField(blank=True, help_text='YYYY-MM or custom key for deduplication.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified.')),
                ('name', models.CharField(help_text='Human-readable template name.', max_length=100)),
                ('code', models.CharField(help_text='Machine identifier (e.g., fee_reminder, attendance_alert).', max_length=50, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', help_text='Delivery channel for this template.', max_length=15)),
                ('subject_template', models.CharField(blank=True, help_text='Subject line with {variable} placeholders.', max_length=200, null=True)),
                ('body_template', models.TextField(help_text='Body with {variable} placeholders.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is enabled.')),
                ('description', models.TextField(blank=True, help_text='Internal notes about when this template is used.', null=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['channel', 'is_active'], name='idx_tmpl_channel_active'),
        ),
        migrations.AddField(
            model_name='notification',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text='Direct FK for enrollment-scoped deduplication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='notification',
            field=models.ForeignKey(blank=True, help_text='Linked notification if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered the email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['enrollment', 'category', 'dedup_key'], name='idx_notif_enroll_dedup'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email', 'sent_at'], name='idx_email_recip_date'),
        ),
    ]
